### ISSUE TITLE
BUG: need to tempate aws creds from cluster-vars.yml values

### ISSUE THREAD

**Issue by usrbinkat** [CodeSparta/sparta#3]
TASK [secrets :  RedHat | Konductor | Infra Automation | secrets | copy | Place AWS Credentials] **************************************************Thursday 21 January 2021  20:57:30 +0000 (0:00:00.027)       0:00:00.869 ******                                                                   
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find or access '/root/platform/secrets/aws/credentials' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}  

manual remediation:
```
mkdir -p /root/platform/secrets/aws
cat <<EOF > /root/platform/secrets/aws/credentials
[default]
aws_access_key_id = AKIXXXXXXXXXXXXXXXXX3R
aws_secret_access_key = kvqXXXXXXXXXXXXXXXXXXXXXXXCW
EOF
```

**Comment by swarred** [comment]
[PR](https://github.com/CodeSparta/sparta/pull/4) was submitted for bug fix
